version: "3.3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    env_file:
      - .env
  mongodb:
    image: mongo:latest
    volumes:
      - ./db:/data/db